Repository AP-Sensing/PhotonPonyOS, pull requests merged in 2023-12, with the labels that each got.

#18 Deleted duplicated btfrs subvolume in kickstart
  ppos.ks
Labels: 🐛 Bug

#14 Using the dts-n62-setup Package For Setup
  fedora-photon-pony-base-packages.yaml
  fedora-photon-pony.yaml
Labels: ✨ Feature

#19 Added a Gitlab CI automation
  .gitlab-ci.yml
  README.md
Labels: 🧱 CI, ✨ Feature

#20 Including the spectrum kernel module inside the base image packages
  fedora-photon-pony-base-packages.yaml
Labels: ✨ Feature
